import type { ModelDef } from "./types";

// Mirrors plato/llm.py:83-98 with cost metadata layered on top.
// Costs are USD per 1K tokens at list price as of 2026-01; update as providers change.
export const MODELS: ModelDef[] = [
  {
    id: "gemini-2.0-flash",
    label: "Gemini 2.0 Flash",
    provider: "gemini",
    maxOutputTokens: 8192,
    temperature: 0.7,
    costInputPer1k: 0.00010,
    costOutputPer1k: 0.00040,
    notes: "Cheap · fast",
  },
  {
    id: "gemini-2.5-flash",
    label: "Gemini 2.5 Flash",
    provider: "gemini",
    maxOutputTokens: 65536,
    temperature: 0.7,
    costInputPer1k: 0.00030,
    costOutputPer1k: 0.0025,
    notes: "Cheap · long output",
  },
  {
    id: "gemini-2.5-pro",
    label: "Gemini 2.5 Pro",
    provider: "gemini",
    maxOutputTokens: 65536,
    temperature: 0.7,
    costInputPer1k: 0.00125,
    costOutputPer1k: 0.010,
    notes: "Strong reasoning",
  },
  {
    id: "gemini-3.1-pro",
    label: "Gemini 3.1 Pro",
    provider: "gemini",
    maxOutputTokens: 65536,
    temperature: 0.7,
    notes: "Frontier reasoning",
  },
  {
    id: "o3-mini",
    label: "o3-mini",
    provider: "openai",
    maxOutputTokens: 100000,
    temperature: null,
    costInputPer1k: 0.00110,
    costOutputPer1k: 0.0044,
    notes: "Strong reasoning",
  },
  {
    id: "gpt-4o",
    label: "GPT-4o",
    provider: "openai",
    maxOutputTokens: 16384,
    temperature: 0.5,
    costInputPer1k: 0.0025,
    costOutputPer1k: 0.010,
  },
  {
    id: "gpt-4.1",
    label: "GPT-4.1",
    provider: "openai",
    maxOutputTokens: 16384,
    temperature: 0.5,
    costInputPer1k: 0.0020,
    costOutputPer1k: 0.0080,
    notes: "Recommended",
  },
  {
    id: "gpt-4.1-mini",
    label: "GPT-4.1 mini",
    provider: "openai",
    maxOutputTokens: 16384,
    temperature: 0.5,
    costInputPer1k: 0.00040,
    costOutputPer1k: 0.0016,
    notes: "Cheap",
  },
  {
    id: "gpt-4o-mini",
    label: "GPT-4o mini",
    provider: "openai",
    maxOutputTokens: 16384,
    temperature: 0.5,
    costInputPer1k: 0.00015,
    costOutputPer1k: 0.00060,
    notes: "Cheap",
  },
  {
    id: "gpt-4.5",
    label: "GPT-4.5 preview",
    provider: "openai",
    maxOutputTokens: 16384,
    temperature: 0.5,
    costInputPer1k: 0.075,
    costOutputPer1k: 0.150,
    notes: "Premium",
  },
  {
    id: "gpt-5",
    label: "GPT-5",
    provider: "openai",
    maxOutputTokens: 128000,
    temperature: null,
    costInputPer1k: 0.0125,
    costOutputPer1k: 0.050,
    notes: "Premium · long output",
  },
  {
    id: "gpt-5-mini",
    label: "GPT-5 mini",
    provider: "openai",
    maxOutputTokens: 128000,
    temperature: null,
    costInputPer1k: 0.00025,
    costOutputPer1k: 0.0020,
    notes: "Cheap · long output",
  },
  {
    id: "gpt-5.5",
    label: "GPT-5.5",
    provider: "openai",
    maxOutputTokens: 128000,
    temperature: null,
    notes: "Availability depends on account",
  },
  {
    id: "gpt-5.5-pro",
    label: "GPT-5.5 Pro",
    provider: "openai",
    maxOutputTokens: 128000,
    temperature: null,
    notes: "Availability depends on account",
  },
  {
    id: "claude-3.7-sonnet",
    label: "Claude 3.7 Sonnet",
    provider: "anthropic",
    maxOutputTokens: 64000,
    temperature: 0,
    costInputPer1k: 0.003,
    costOutputPer1k: 0.015,
  },
  {
    id: "claude-4-opus",
    label: "Claude 4 Opus",
    provider: "anthropic",
    maxOutputTokens: 32000,
    temperature: 0,
    costInputPer1k: 0.015,
    costOutputPer1k: 0.075,
    notes: "Premium reasoning",
  },
  {
    id: "claude-4.1-opus",
    label: "Claude 4.1 Opus",
    provider: "anthropic",
    maxOutputTokens: 32000,
    temperature: 0,
    costInputPer1k: 0.015,
    costOutputPer1k: 0.075,
    notes: "Recommended for retries",
  },
  {
    id: "claude-4.7-opus",
    label: "Claude 4.7 Opus",
    provider: "anthropic",
    maxOutputTokens: 32000,
    temperature: null,
    notes: "Premium reasoning",
  },
  {
    id: "deepseek-v4",
    label: "DeepSeek V4 Flash",
    provider: "huggingface",
    maxOutputTokens: 65536,
    temperature: 0.7,
    notes: "HF Inference Providers",
  },
  {
    id: "deepseek-v4-pro",
    label: "DeepSeek V4 Pro",
    provider: "huggingface",
    maxOutputTokens: 65536,
    temperature: 0.7,
    notes: "HF Inference Providers",
  },
  {
    id: "Qwen/Qwen3.6-27B",
    label: "Qwen3.6 27B",
    provider: "huggingface",
    maxOutputTokens: 65536,
    temperature: 0.7,
    notes: "HF Inference Providers",
  },
  {
    id: "meta-llama/Llama-3.3-70B-Instruct",
    label: "Llama 3.3 70B Instruct",
    provider: "huggingface",
    maxOutputTokens: 32768,
    temperature: 0.7,
    notes: "HF gated access may apply",
  },
  {
    id: "moonshotai/Kimi-K2.6",
    label: "Kimi K2.6",
    provider: "huggingface",
    maxOutputTokens: 65536,
    temperature: 0.7,
    notes: "HF Inference Providers",
  },
  {
    id: "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4",
    label: "Nemotron 3 Super 120B",
    provider: "huggingface",
    maxOutputTokens: 32768,
    temperature: 0.7,
    notes: "HF Inference Providers",
  },
];

export const MODELS_BY_ID = Object.fromEntries(MODELS.map((m) => [m.id, m]));

export const MODEL_GROUPS = [
  { provider: "anthropic" as const, label: "Anthropic" },
  { provider: "openai" as const, label: "OpenAI" },
  { provider: "gemini" as const, label: "Google" },
  { provider: "huggingface" as const, label: "Hugging Face" },
];

export function modelsForProvider(provider: ModelDef["provider"]): ModelDef[] {
  return MODELS.filter((m) => m.provider === provider);
}

export function estimateCost(model: ModelDef, inputTokens: number, outputTokens: number): number {
  const inputCost = ((model.costInputPer1k ?? 0) * inputTokens) / 1000;
  const outputCost = ((model.costOutputPer1k ?? 0) * outputTokens) / 1000;
  return Math.round((inputCost + outputCost) * 10000); // return in cents (0.01 = 1 cent), with 4-decimal precision
}
